url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Junda (Joshua) Wu" # the name of your site, e.g. ACME Corp.
description: "Email: juw069 AT ucsd.com"
